# Generated by Django 3.1.5 on 2021-05-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210416_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address1',
            field=models.TextField(null=True, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address2',
            field=models.TextField(null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.TextField(null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.TextField(null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.TextField(null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zipcode',
            field=models.IntegerField(null=True, verbose_name='Zipcode'),
        ),
    ]
