# Generated by Django 3.1.5 on 2021-04-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210416_2103'),
        ('travel', '0002_auto_20210419_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ManyToManyField(to='accounts.UserProfile'),
        ),
    ]
