# Generated by Django 3.1.5 on 2021-04-27 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20210416_2103'),
        ('travel', '0002_auto_20210419_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('vote', models.IntegerField(default=0)),
                ('trip_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='accounts.userprofile')),
            ],
        ),
    ]
