# Generated by Django 3.1.5 on 2021-05-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_auto_20210506_2250'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('suggestions_id', 'user_id'), name='unique_suggestions_id_user_id'),
        ),
    ]
